// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvvnvtvanomyuvqamamj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2dm52dHZhbm9teXV2cWFtYW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Njg5NzMsImV4cCI6MjA2MTI0NDk3M30.-tag-M3Uw_r3kecChxnZ5o0i-5DpxWDr2ecMvTGoZi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);